/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as DemRouteImport } from './routes/dem'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CapasRouteImport } from './routes/capas'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const DemRoute = DemRouteImport.update({
  id: '/dem',
  path: '/dem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CapasRoute = CapasRouteImport.update({
  id: '/capas',
  path: '/capas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/capas': typeof CapasRoute
  '/contacto': typeof ContactoRoute
  '/dem': typeof DemRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/portafolio': typeof PortafolioRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/capas': typeof CapasRoute
  '/contacto': typeof ContactoRoute
  '/dem': typeof DemRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/portafolio': typeof PortafolioRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/capas': typeof CapasRoute
  '/contacto': typeof ContactoRoute
  '/dem': typeof DemRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/portafolio': typeof PortafolioRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/capas'
    | '/contacto'
    | '/dem'
    | '/galeria'
    | '/login'
    | '/portafolio'
    | '/servicios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/capas'
    | '/contacto'
    | '/dem'
    | '/galeria'
    | '/login'
    | '/portafolio'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/capas'
    | '/contacto'
    | '/dem'
    | '/galeria'
    | '/login'
    | '/portafolio'
    | '/servicios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CapasRoute: typeof CapasRoute
  ContactoRoute: typeof ContactoRoute
  DemRoute: typeof DemRoute
  GaleriaRoute: typeof GaleriaRoute
  LoginRoute: typeof LoginRoute
  PortafolioRoute: typeof PortafolioRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dem': {
      id: '/dem'
      path: '/dem'
      fullPath: '/dem'
      preLoaderRoute: typeof DemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capas': {
      id: '/capas'
      path: '/capas'
      fullPath: '/capas'
      preLoaderRoute: typeof CapasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CapasRoute: CapasRoute,
  ContactoRoute: ContactoRoute,
  DemRoute: DemRoute,
  GaleriaRoute: GaleriaRoute,
  LoginRoute: LoginRoute,
  PortafolioRoute: PortafolioRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
